name: udevs_phone_number
description: A new Flutter package.
version: 0.0.1
homepage: https://github.com/MobileUdevs/udevs_phone_number.git

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.3
  libphonenumber_plugin: ^0.2.3
  equatable: ^2.0.5
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  plugin:
    platforms:
      android:
        package: uz.udevs.udevs_phone_number
        pluginClass: UdevsPhoneNumberPlugin
      ios:
        pluginClass: UdevsPhoneNumberPlugin
      linux:
        pluginClass: UdevsPhoneNumberPlugin
      macos:
        pluginClass: UdevsPhoneNumberPlugin
      windows:
        pluginClass: UdevsPhoneNumberPluginCApi
      web:
        pluginClass: UdevsPhoneNumberWeb
        fileName: udevs_phone_number_web.dart

  assets:
     - assets/flags/
